name: Run tests and upload coverage
description: Run Codecov testing on a push and/or on a manual trigger.

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run tests
        run: |
          uv run --with pytest-cov --with nicegui --with course-constraint-scheduler \
          pytest --cov=. --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          
